#pragma once

#define ICON_FONT_ALERT_CIRCLE_OUTLINE u8"\uf5d6"
#define ICON_FONT_BELL_CIRCLE_OUTLINE u8"\ufd37"
#define ICON_FONT_SPACE_INVADERS u8"\ufba5"
#define ICON_FONT_CHEVRON_DOWN u8"\uf140"
#define ICON_FONT_CHEVRON_LEFT u8"\uf141"
#define ICON_FONT_CHEVRON_RIGHT u8"\uf142"
#define ICON_FONT_CHEVRON_UP u8"\uf143"
#define ICON_FONT_TRASH_CAN u8"\ufa78"
#define ICON_FONT_REFRESH u8"\uf450"
#define ICON_FONT_BUG u8"\uf0e4"

#define BAR_LABEL_INFOS ICON_FONT_ALERT_CIRCLE_OUTLINE
#define BAR_LABEL_WARNINGS ICON_FONT_BELL_CIRCLE_OUTLINE
#define BAR_LABEL_ERROR ICON_FONT_BUG

#define MENU_LABEL_REFRESH ICON_FONT_REFRESH
#define MENU_LABEL_CLEAR ICON_FONT_TRASH_CAN
#define MENU_LABEL_ARROW_LEFT ICON_FONT_CHEVRON_LEFT
#define MENU_LABEL_ARROW_RIGHT ICON_FONT_CHEVRON_RIGHT
#define MENU_LABEL_ARROW_UP ICON_FONT_CHEVRON_UP
#define MENU_LABEL_ARROW_BOTTOM ICON_FONT_CHEVRON_DOWN
