name: Win

on:
  push:
    branches:
    - master

jobs:
  build_Win_latest:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: checkout submodules
      run : git submodule update --init --recursive 
    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ezRenamer_full_sources.zip
        path: .
